### ISSUE TITLE
Endpoint for DSM tiff files

### ISSUE THREAD

**Issue by neelduttahere** [developmentseed/titiler#143]
Hey, I was recently going through your library and it's API endpoints, however I couldn't figure how to generate tiles for geoTiff files containing DSM/DEM contents. 

I am very new this domain for COGs, so any help would be really appreciated. Thanks in advance!

**Comment by vincentsarago** [comment]
@neelduttahere I'm not sure to fully understand your question. We'll need specific example/comments to be able to answer.

DSM/DEM GeoTIFF are usually stored as float values, which will require `rescaling` to be able to create map tiles (jpeg/png), because you can only encode `uint8` values in visible image (from 0 to 255).

I'm going to close this issue because I don't think it's related to any `Issue` with TiTiler itself but I'll try to add some documentation about the concept of Dynamic Tiling.

**Comment by neelduttahere** [comment]
Thank you for the information and now it all makes sense to me.
