### ISSUE TITLE
Create_CustomSentinel2Tiler.ipynb notebook is broken

### ISSUE THREAD

**Issue by drnextgis** [developmentseed/titiler#208]
* in the first section "Create the CustomTiler" instead of `from titiler.models.dataset import Info, Metadata` should be `from rio_tiler.models import Info, Metadata`
* `optquery` variable is not defined

**Comment by drnextgis** [comment]
Thanks @vincentsarago, great job! We are planing to start using Titiler here so in order to be more familiar with code I'm going to pick something else to fix from the backlog.

**Comment by vincentsarago** [comment]
thanks @drnextgis 

>  so in order to be more familiar with code I'm going to pick something else to fix from the backlog.

- Right now the highest priority is to find a solution for https://github.com/developmentseed/titiler/issues/186 but I think the fix is on rasterio side. 

- https://github.com/developmentseed/titiler/issues/153 also needs more discussion. 

- https://github.com/developmentseed/titiler/issues/193 I've started something on my side, but I'm not 💯 sure we have to do this

We are always looking for contribution on the DOC side. Like I really want to add docstring (google style) to all the methods/function so we can add API documentation in the online doc. Other documentation update would be really appreciated.
