### ISSUE TITLE
remove default middlewares

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#269]
ref: https://github.com/developmentseed/titiler/discussions/268

I don't think it's up to TiTiler to define application settings like CORS and response compression. This could be easily added by a user on their own application

```python
from brotli_asgi import BrotliMiddleware

from titiler.main import app

app.add_middleware(BrotliMiddleware, minimum_size=0, gzip_fallback=True)
``` 

cc @drnextgis @geospatial-jeff @kylebarron

**Comment by drnextgis** [comment]
Totally agree. I was a little bit surprised to see this functionality (response compression) as part of the application itself. It is usually configured on the application server level.

**Comment by kylebarron** [comment]
I think this was originally done as part of the work to support Numpy tile output, because by default that data is uncompressed, and I think it was planned to only apply that as necessary but hadn't happened yet.

I don't know how much appetite there is for Titiler to really support Numpy tile output, but my stance is that if we want to truly support it, compression should be on by default for that output. Numpy output (especially with a mask) is quite large without compression, and any end user who wants to use both Numpy and other output formats will have the same issue as you: without digging into the application it seems hard to configure compression only for selected outputs.

I don't know fastapi/starlette as well as @vincentsarago and @geospatial-jeff, but I'd expect there's a way to apply middleware only to certain outputs, e.g. to be able to say "use this middleware only on outputs of type `application/octet-stream`". If that exists, then seems easy to implement "apply compression by default only for Numpy responses".

> I was a little bit surprised to see this functionality (response compression) as part of the application itself

Not sure I follow, but if I understand correctly `main.py` is expected to be overridden by all except introductory end-users (for whom default compression on uncompressed file types is a benefit). So it would be very easy for you to reuse all of titiler without any given middleware by copying `main.py` yourself.

**Comment by vincentsarago** [comment]
just adding that to me it's not clear if headers get added to tile requests when using web map libraries 🤷‍♂️

**Comment by kylebarron** [comment]
> just adding that to me it's not clear if headers get added to tile requests when using web map libraries 🤷‍♂️

I believe every network request a browser ever makes includes these `Accept-Encoding` headers. If I look at a random network request on this page, I can see plenty of default headers
![image](https://user-images.githubusercontent.com/15164633/111234680-b576c780-85b4-11eb-86b7-6bad86581452.png)

Setting those headers is at the browser-level, not the JS level. Furthermore, it looks like it's _impossible_ for JS to override that or any other "forbidden header" https://stackoverflow.com/a/63855008 https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by drnextgis** [comment]
> Not sure I follow, but if I understand correctly main.py is expected to be overridden by all except introductory end-users (for whom default compression on uncompressed file types is a benefit).

I meant that compression might be configured (even for selected outputs) outside of Titiler. For example in case of k8s it might be done by adding something like this [here](https://github.com/developmentseed/titiler/blob/ab5342712812eb05e2a7af8d6c13be3e828ece6a/deployment/k8s/titiler/values.yaml#L18):
```
annotations:
  kubernetes.io/ingress.class: nginx
  nginx.org/server-snippets: |
    gzip on;
    gzip_types application/x-binary;
```

**Comment by vincentsarago** [comment]
@kylebarron I get your point, but IMO, titiler shouldn't be responsible for the `application`. we ship a default app but I see it only as a demo. For production application I expect the user to add custom thing like middleware.

I think it would be pretty straight forward for a user to create a custom middleware that encode only npy response.

**Comment by kylebarron** [comment]
> we ship a default app but I see it only as a demo

I think there's a tension here. If the default app is only a "demo" and shouldn't go into production, we should do things like removing the built Titiler Docker image. To me, having a docker image on Docker Hub says "this image is deploy-ready, just set some environment variables to your configuration". If that isn't the case, then that image shouldn't exist, because it'll make it easier for newcomers to shoot themselves in the foot.

**Comment by kylebarron** [comment]
> It seems there is no easy way for doing that.

> I think it would be pretty straight forward for a user to create a custom middleware that encode only npy response.

Those two arguments are contradictory...

**Comment by vincentsarago** [comment]
@kylebarron 

> Those two arguments are contradictory...

Indeed they are, and in fact @drnextgis is right, creating custom middleware that do no apply compression based on a media_type is not as easy.

> I think there's a tension here. If the default app is only a "demo" and shouldn't go into production, we should do things like removing the built Titiler Docker image. To me, having a docker image on Docker Hub says "this image is deploy-ready, just set some environment variables to your configuration". If that isn't the case, then that image shouldn't exist, because it'll make it easier for newcomers to shoot themselves in the foot.

To me it's: hey there is a docker image, if you want to try you don't have to install anything. Like the GDAL docker image, you can use them in production but if you want something focused on performance, maybe you need to create one yourself 

Here we have two choice:
- keep the default middleware, which re-compress body (only good when using uncompress data format like tiff and numpy-tile)
- remove the middleware and let the user figure out what to do

IMO, re-compressing data is bad. We can work on a solution that enables compression for some specific mediatype but until someone propose a good solution I'm in favour of removing the middleware.

cc @geospatial-jeff

**Comment by geospatial-jeff** [comment]
IMO slimmer is better.  I don't think we should include things in the app by default that aren't necessarily required, and middleware definitely falls into this category.

**Comment by kylebarron** [comment]
> Here we have two choice:
> 
> * keep the default middleware, which re-compress body (only good when using uncompress data format like tiff and numpy-tile)
> * remove the middleware and let the user figure out what to do

Well I've never advocated for the first; re-compressing the body is unequivocally bad. My argument from the beginning of this issue is there's an option 3: figuring out how to add middleware to only compress uncompressed responses. After all there are plenty of non-image endpoints that return JSON and would be good to compress responses for.

Still, there's a tension here, are we planning to remove _all_ the middlewares?? Then the default app won't even have CORS headers and won't be very usable.

IMO `main.py` is only used in the "demo" app; it's really not the "public export" of titiler. The public exports of titiler are all the things that `main.py` are referencing. Therefore having good defaults in `main.py` is a good thing, so that newcomers to the project can easily deploy something with sensible defaults without needing to customize everything.

**Comment by vincentsarago** [comment]
> Therefore having good defaults in main.py is a good thing

a good default is IMO without the middleware! Mostly because, there isn't an easy way to know which response are already compressed (e.g a PNG could be encored without compression, a GeoTIFF could already be compressed...)

> Then the default app won't even have CORS headers and won't be very usable.

We can argue about this. if you use the default viewer provided but the app it will work.

**Comment by kylebarron** [comment]
Well first, let me be clear that I'm arguing not for myself, since I personally am happy to customize the middlewares I use. I think removing all the middleware will hurt the marginal consumer of the library and that lowering the barrier to entry is a good thing. It's better IMO to have sensible defaults on the default app so that new users of the library get a working deployment, and then later on can tweak settings as they need to.

The question then is which middlewares are included by default. I disagree that _all_ middlewares should be removed by default, because I think that makes it harder for a new user to get up and running.

I think either of these two things are the best options:
1. Remove compression for all response types, but also remove any reference to numpy tiles in the top-level README (and only have references in the detailed docs), because uncompressed numpy tiles are not something that should be promoted. In the detailed docs on the supported formats there should be an "admonition warning (i.e. `!!! warning` in mkdocs)" that numpy tiles provided by the endpoint are not compressed, that compression is very important for this format in particular, and that the user must implement this themselves.
2. Implement selective compression by default for all text responses and numpy tiles.

**Comment by vincentsarago** [comment]
- not compressing `uncompressed` data is bad (especially for tif and numpytile)
- compressing `compressed` data is bad 
- creating a custom middleware to handle compression depending the response media-type is not straight forward
- having a good/user friendly default app is nice (a minimal production ready app with CORS and compression)

Just looking at Martin and pg_tileserver, they do ship CORS and compression by default, so maybe it's fine to keep them too 🤷‍♂️

**Comment by drnextgis** [comment]
> Just looking at Martin and pg_tileserver, they do ship CORS and compression by default

For vector tiles it makes sense https://blog.cyclemap.link/2020-02-02-optimizing-vectortiles/#gzip

**Comment by vincentsarago** [comment]
closing this in favour of #312 which should allow customization to avoid re-compressing compressed data.
