### ISSUE TITLE
we need a better UI

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#27]

**Comment by vincentsarago** [comment]
right now the default UI fetch the dataset metadata (info + stats) when openning a new dataset. This helps when we are dealing with non-byte data (rescaling the value from min/max found in the stats) 

https://github.com/developmentseed/titiler/blob/9a8d57918fd6f5e908308a01eed6761773959406/src/titiler/application/titiler/application/templates/cog_index.html#L754

I think we should make `metadata` fetching optional (and thus making the histogram optional too)

**Comment by dchirst** [comment]
Hey @vincentsarago. This issue is pretty old, but I'd be interested in taking it on. Do you have any other ideas on how you'd like to improve the UI, or has most of the work for this been done already? 

Also, I'm not sure I fully understand how the UI here interfaces with [rio-viz](https://github.com/developmentseed/rio-viz) - should it be all one codebase (in titiler.local like [this issue says](https://github.com/developmentseed/rio-viz/issues/50)), or should development be done in `rio-viz` instead?

**Comment by vincentsarago** [comment]
titiler and rio-viz are two different project but they share a lot (well now rio-viz depends on titiler.core 😅) 

titiler.extensions's viewers are really close to the one in rio-viz and I usually experiment first in rio-viz before changing the UI in titiler. About my last comment, I already made the change in titiler's viewer (we now only fetch the `info` for the dataset and then the user can fetch the statistics) 

That's said, the viewers are pretty old and written in `pure` javascript/css. I'm sure we can do better!!! I'm not a frontend designer/developper so I prefer let other do this task 😂 

Note: Designing a frontend for titiler client is going to be quite complex so if we really want to do this I should also check internally if some of our designers want to help (👋 @LanesGood @ricardoduplos) but I feel you have a great knowledge of titiler already so I'm eager to ear what you have in mind 😃

**Comment by dchirst** [comment]
Right! Maybe this should be a discussion in that case, rather than an Issue? There are so many ways that we could start addressing this, ranging from relatively simple UI changes to larger full rewrites.
