### ISSUE TITLE
add mosaics

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#3]

**Comment by vincentsarago** [comment]
## Mosaic Store 

Following some discussion on slack with @geospatial-jeff we need to choose: 
- what backend we support (file, s3, http, dynamoDB, stac) 
- how the user pass the mosaicjson (url, id) 
- do we allow external mosaic ? 


in cogeo-mosaic-tiler, the mosaicjson is passed either via `url` or via a `mosaicid` (prefered method). With the mosaicid we know (app owner) that the mosaic will be store in `s3://${mosaicbuck}/${mosaicprefix}/{mosaicid}.json.gz` so we added endpoint like `/tiles/{mosaicid}/z/x/y`

The mosaicid is created using the sha224 of the mosaic body. 

here is how we reconstruct the path (the datastore is S3 and is defined via env variable)
https://github.com/developmentseed/cogeo-mosaic-tiler/blob/master/cogeo_mosaic_tiler/handlers/app.py#L60-L67

#### IMO

- what backend we support (file, s3, http, dynamoDB, stac) 

For now S3 / File (EFS) / DynamoDB is fine, but titiler SHOULD have a default backend defined by a setting (e.g `s3://bucket/mosaics/` or `dynamodb://`

- how the user pass the mosaicjson (url, id) 

as for cogeo-mosaic-tiler, I think uniq ID for a mosaic is fine. That's said I'd love to use something more intelligible.

in #40 I throw the idea of using id like mapbox tileset: `{user}.{layername}`. This will also be good for a long term goal if we add `users` to titiler (like user have some COGs on our bucket, they can create mosaic ... ) 

- do we allow external mosaic ? 

I'll tend to answer NO, but a user could post a mosaic to add it to our system.

**Comment by geospatial-jeff** [comment]
> For now S3 / File (EFS) / DynamoDB is fine, but titiler SHOULD have a default backend defined by a setting (e.g `s3://bucket/mosaics/` or `dynamodb://`

I think it should support all backends and raise `400 Bad Request` status code when trying to perform an unsupported operation (ex. write to HTTP backend).  I do like the idea of defining a default backend so you can do `id` lookups to the default backend and `url` lookups to any backend.  Could also encode the name of the backend into the id and not use `url` lookups at all.


> in #40 I throw the idea of using id like mapbox tileset: `{user}.{layername}`. This will also be good for a long term goal if we add `users` to titiler (like user have some COGs on our bucket, they can create mosaic ... )

I think having a user table is a good long play, but that is a larger change since it would require a database as well.  I agree that unique ID is fine for initial support of mosaics


> I'll tend to answer NO, but a user could post a mosaic to add it to our system.

I think scoping of permissions should be deferred to the particular backend and the API should raise a `401 Unauthorized` status code if a user tries to access a mosaic which they don't have access to.  For example if you have a mosaicjson stored on S3 access should be limited at the IAM level rather than relying on the API.

A separate but related topic is user-based permissions within an organization which I think are a great idea if titiler ends up using a user table.

**Comment by vincentsarago** [comment]
done in #40
