### ISSUE TITLE
mosaicJson use wmsExtension. LAYERS parameter  not support mosaicJson 

### ISSUE THREAD

**Issue by RS-Y** [developmentseed/titiler#942]
TiTiler WMS TiTiler WMS COG URLs specified in the "LAYERS" parameter will show up as available layers application/vnd.ogc.wms_xml image/png image/jpeg image/jpg image/webp image/jp2 image/tiff; application=geotiff text/html application/vnd.ogc.se_xml application/vnd.ogc.se_inimage application/vnd.ogc.se_blank TiTiler WMS TiTiler WMS COG URLs specified in the "LAYERS" parameter will show up as available layers EPSG:4326 /home/ai/data1/neu_gis/1/cog/1806518206549946368/9y6pqo1l /home/ai/data1/neu_gis/1/cog/1806518206549946368/9y6pqo1l

**Comment by vincentsarago** [comment]
@RS-Y can you please be a bit more clear in your issue description 🙏

**Comment by RS-Y** [comment]
@vincentsarago When I use MosaicTilerFactory and set wmsExtension(), I encounter an error when I try to get layer basic information using {ip:host}/mosaicjson/wms?layers={url}mosaic.json&SERVICE=WMS&REQUEST=GetCapabilities&version=1.1.1.

**Comment by vincentsarago** [comment]
I don't think the wmsExtension will work with Mosaic backend. sorry If this not clear from the documentation. 

mostly because the wmsExtension use the `part` method which is not implemented in the default mosaic backends https://github.com/developmentseed/cogeo-mosaic/blob/main/cogeo_mosaic/backends/base.py#L390-L392
